include ../config.mk

# You should customize INSTALL_ROOT in local_config.mk to install
# to different than default

# When changing this, you need to run 'mrproper'
INSTALL_PREFIX = /usr

.NOTPARALLEL: install

install: prepare-ghdl install-ghdl install-ghdllib

include guess-config.mk
include ghdl-outside.mk

check:
	@echo $(GCC_SRC)
	@echo $(GHDL_GCC_BUILDDIR)

mrproper:
	rm -fr $(GHDL_BUILDDIR) $(GHDL_GCC_BUILDDIR)
