include ../config.mk

INSTALL_ROOT = /media/sandbox

INSTALL_PREFIX = /usr

install: install-ghdl install-ghdllib

include guess-config.mk
include ghdl-outside.mk

check:
	@echo $(GCC_SRC)
	@echo $(GHDL_GCC_BUILDDIR)

mrproper:
	rm -fr $(GHDL_BUILDDIR) $(GHDL_GCC_BUILDDIR)
