FROM ghdl/ghdl:buster-gcc-7.2.0 

RUN apt-get update; apt-get install -y \
	make gnat-7 g++-7 git wget libz-dev texinfo xz-utils bzip2 file

RUN useradd -u 1000 -g 100 -m -s /bin/bash build && \
    mkdir /home/build/src && \
    mkdir /home/build/build && \
    mkdir /home/build/scripts

COPY recipes /home/build/scripts/recipes
COPY configs /home/build/scripts/configs
COPY docker_config.mk /home/build/scripts/

RUN chown -R build /home/build
USER build
WORKDIR /home/build
